name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "[major]"
        minor_pattern: "[minor]"
        version_format: "${major}.${minor}.${patch}-prerelease_${increment}"
      id: version

    - name: login Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: build image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t $DOCKER_USER/graph-ql:$VERSION .
        docker build -t $DOCKER_USER/graph-ql:latest .

    - name: push image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build $DOCKER_USER/graph-ql:$VERSION
        docker build $DOCKER_USER/graph-ql:latest
        
      
